logging:
  config:classpath:log4j2-boot-pro.xml
user:
  author: "知了一笑"
  title: "SpringBoot 2.0 程序开发"
  time: "2019-07-05"

spring:
  datasource:
    # 数据源一：data_one 库
    primary:
      # 2.0开始的版本必须这样配置
      jdbc-url: jdbc:mysql://localhost:3306/data_one
      #url: jdbc:mysql://localhost:3306/data_one
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    # 数据源二：data_two 库
    secondary:
      # 2.0开始的版本必须这样配置
      jdbc-url: jdbc:mysql://localhost:3306/data_two
      #url: jdbc:mysql://localhost:3306/data_two
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver